name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: CD to my-app  & install dependencies
        run: |
          cd my-app
          npm install
      - name: Build
        run: |
          cd my-app
          npm run build